test: demonstrate an issue with aggregate constraints
With these changes present, running the test suite causes the
compilation step to fail with the following error:

== Compilation error in file test/support/schema.ex ==
** (Absinthe.Schema.Error) Compilation failed:
---------------------------------------
/ash/ash_graphql/lib/resource/resource.ex:3704

In field Latest_comment_type, :post_latest_comment_type is not defined in your schema.

Types must exist if referenced.
  (absinthe 1.7.5) lib/absinthe/schema.ex:392: Absinthe.Schema.__after_compile__/2
  (stdlib 5.0.2) lists.erl:1594: :lists.foldl/3